name: Apply Dotfiles

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  macos-test:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Install chezmoi
        run: |
          sh -c "$(curl -fsLS get.chezmoi.io)" -- -b "$HOME/.local/bin"
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Initialize chezmoi
        env:
          CHEZMOI_EMAIL: "ci@example.com"
          CHEZMOI_USER: "CI User"
        run: chezmoi init https://github.com/yosmoc/dotfiles.git

      - name: Run chezmoi apply
        run: chezmoi apply

  archlinux-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Setup and apply chezmoi
        uses: ./.github/actions/setup-chezmoi
        with:
          repository: https://github.com/yosmoc/dotfiles.git
